#!/usr/bin/env bash

FOLDER=~/pictures/wallpapers/
USE_RANDOM=0

pywal16() {
	# colorz and haishoku
	wal -i $WALLPAPER --cols16 lighten --contrast 4.5 --saturate 0.6 -s --backend haishoku
}

fill-and-merge() {
	feh --bg-fill $1
	ln -sf ~/.cache/wal/colors.Xresources ~/.Xresources
	cat ~/.Xresources ~/.cache/wal/xrdb_extra | xrdb -merge
	xdotool key super+ctrl+backslash # xrdb refresh keybind
}

apply-kitty-theme() {
	local THEME_FILE="$HOME/.cache/wal/colors-kitty.conf"
	for socket in /tmp/kitty_pywal-*; do
		if [[ -S "$socket" ]]; then
			kitty @ --to unix:"$socket" set-colors --all --configured "$THEME_FILE"
		fi
	done
}

while getopts ":i:r" opt; do
	case $opt in
	i) WALLPAPER=${OPTARG} ;;
	r) USE_RANDOM=1 ;;
	esac
done

if [[ "$USE_RANDOM" == "1" ]]; then
	FILE=$(ls "$FOLDER" | shuf -n 1)
	WALLPAPER=$FOLDER$FILE
	pywal16
	fill-and-merge $WALLPAPER
	apply-kitty-theme
	exit
elif [[ -n $WALLPAPER ]]; then
	pywal16
	fill-and-merge $WALLPAPER
	apply-kitty-theme
	exit
else
	if command -v nsxiv >/dev/null; then
		WALLPAPER=$(nsxiv -otb $FOLDER/*)
		pywal16
		fill-and-merge $WALLPAPER
		apply-kitty-theme
	else
		echo "nsxiv not found"
		exit 1
	fi
fi
