#!/bin/bash

if [[ -n "$1" ]]; then
	WALLPAPER="$1"
else
	FOLDER=~/Pictures/wallpapers/
	FILE=$(ls "$FOLDER" | shuf -n 1)
	WALLPAPER=$FOLDER$FILE
fi

wal -i $WALLPAPER --contrast 3 --saturate 0.4 -b 202020         

feh --bg-scale $WALLPAPER

ln -sf ~/.cache/wal/colors.Xresources ~/.Xresources
cat ~/.Xresources ~/.cache/wal/xrdb_extra | xrdb -merge
xdotool key super+ctrl+backslash # xrdb refresh keybind
